### ISSUE TITLE
Require is not defined

### ISSUE THREAD

**Issue by MrDaGree** [julian-alarcon/prospect-mail#189]
After downloading the deb package and trying to see if this would actually give me desktop notifications I get this error:

![image](https://user-images.githubusercontent.com/5050898/138341600-e7fc4a03-ce38-41b0-ab4a-4ff0158436ca.png)
![image](https://user-images.githubusercontent.com/5050898/138341636-a2bf13dd-bb32-4c81-9ee3-201770a3c532.png)

**Comment by MagiusCHE** [comment]
Fixed.

Waiting for pull-request to be merged, you can compile and use my fork.

https://github.com/MagiusCHE/prospect-mail

**Comment by MagiusCHE** [comment]
I've commented the fix to enable `contextisolation` and `nodeintegration` during creation of BrowserWindow.
![immagine](https://user-images.githubusercontent.com/46496052/146178637-8dd3b0f1-3162-4929-b5c3-311581bd3609.png)

I think it is safe to enable it but we should consider Electron removed default TRUE to `nodeIntegration` and default FALSE to `contextIsolation` for security reason.

@julian-alarcon let me know if it is ok for you and i will removed the comment to fix `require is not defined` and let the notification system works again.

**Comment by MagiusCHE** [comment]
@julian-alarcon can you assign this to me? ( so i can found in my Issue tab :-) )

**Comment by zeitounator** [comment]
@MagiusCHE  @julian-alarcon Disabling context isolation is actually breaking SSO corporate login for any login page using javascript and this has been going on since version 0.5.0. Context isolation is on by default in all recent electon releases. If something is broken with contextIsolation on, it should be fixed by [implementing the migration scenario proposed on electron documentation site](https://www.electronjs.org/docs/latest/tutorial/context-isolation). Turning it off is a workaround not a solution. For specific cases, there's is an [ongoing PR which would let users turn it off by configuration while switching it back on by default](#312).
