### ISSUE TITLE
Links open inside Prospect Mail window, instead of a browser

### ISSUE THREAD

**Issue by SeppoTakalo** [julian-alarcon/prospect-mail#240]
There has been some changes apparently in Outlook Web, as Prospect Mail have not changed.

This week, I started to notice that when ever I try to click any link inside the email, it opens up inside Prospect Mail window. And because there is no navigation buttons, I cannot anymore get back to my email.

**Comment by murturn** [comment]
I see the same. Using the navigation buttons on the side of my mouse does work to return to the mailbox, but no other way is available as far as I can tell.

**Comment by PocketSam** [comment]
Did someone found a way to fix this?

**Comment by keirak420** [comment]
This does not appear to be a "Prospect Mail" issue but rather SnapCraft. I copied the repo, compiled the Debian version, and installed it through the OS. It now appears to be working normally for me. I opted to use https://github.com/kemoycampbell/prospect-mail instead as he has incorporated a "right" mouse click menu that allows you to copy links as well but I did test both.

Test it out, uninstall the SnapCraft version compile your Linux distro version, and try that way. Hopefully, this works for you guys as well. Good luck.

**Comment by keirak420** [comment]
Ok, so I just reinstalled the SnapCraft version, and changed these lines:
`{
    "urlMainWindow":"https://outlook.live.com/mail",
    "urlsInternal":["outlook.com", "live.com"],
    "urlsExternal":["outlook.com", "live.com"]
}`

to:

`{
    "urlMainWindow":"https://outlook.live.com/mail"
}`

I had to quit and restart Prospect Mail as reload didn't seem to change this behavior.
At least for now, the links are redirected to a browser, I am not sure how this will impact other links moving forward. Alternatively, use Kemoy Campbell's version as it at least allows you to right-mouse-click and copy.


Keira

**Comment by zeldigas** [comment]
I've tried solution from @keirak420 but it does not seem to work. From js logic all is fine, and exactly the branch that should open link in browser is executed, but in fact page is still opened inside prospect's window.

Here is the log that I can see, hope it can help identify issue. Maybe the root cause is ibus connectivity issue as I see some warning about it?
```
(prospect-mail:123655): Gtk-WARNING **: 17:54:16.798: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name
Loaded settings {
  outlookUrl: 'https://outlook.office.com/mail',
  deeplinkUrls: [
    'outlook.live.com/mail/deeplink',
    'outlook.office365.com/mail/deeplink',
    'outlook.office.com/mail/deeplink',
    'outlook.office.com/calendar/deeplink'
  ],
  outlookUrls: []
}
[123735:0920/175417.004319:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[123655:0920/175417.557710:ERROR:browser_main_loop.cc(269)] Gdk: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
initialMinimization.domReady false

(prospect-mail:123655): IBUS-WARNING **: 17:54:18.914: Unable to connect to ibus: Could not connect: Connection refused
Open in browser: https://outlook.office.com/mail/safelink.html?....(long url here from email, that should be really matter)
```

**Comment by chahatupreti** [comment]
Any update on this?

**Comment by DenisBY** [comment]
I had to switch to Freelook because of this and Freelook doesn't have this issue.

**Comment by adimitr** [comment]
Just confirming that I also see the issue, but started seeing it maybe a month ago or so. Not sure why it manifested later than the rest of you. Thanks for the posts. I will try some of the configurations suggested here.

**Comment by negesti** [comment]
Seeing the same problem, the logs shows "opening in browser" but the link is openend inside Prospect Mail :(
```

Open in browser: https://outlook.office.com/mail/safelink.html?url=<damnLongUrlNobodyCanRead>

```

**Comment by paulquevedojdrf** [comment]
This started happening to me because my company enabled some outlook `safelink` policy thing which directs all links through `https://outlook.office.com/mail/safelink.html?url=<your link>` 
Given that the common URL prefix `https://outlook.office.com/mail` is the same to all other internal outlook links, I don't think this can be worked around via `settings.json`. 
I think the regex logic for determining when to open in a new window needs have to support for exclusion patterns.
https://github.com/julian-alarcon/prospect-mail/blob/04e96a1148530a25b09be7c966f4f8861b208a96/src/controller/mail-window-controller.js#L243-L261

**Comment by pkeir** [comment]
I am also affected by this. Whenever I click on a link, it opens within Prospect Mail. I am then unable to return to Prospect Mail. My best option is then to close Prospect Mail, and click "Quit" via right-click on the unwanted Prospect Mail icon at the top bar of Gnome (Ubuntu).

Is there perhaps a keyboard shortcut for "Back" (previous page), which might already be available?

**Comment by dmdalmas** [comment]
Best work around I have found is to alt+F4 the prospect-mail window and relaunch the program. This keeps prospect-mail running in the background but seems to reset the session and brings you back to mail.

**Comment by pkeir** [comment]
Thanks. I tried that, but bizarrely it seems I have to perform those actions twice before it works (using either ALT-F4 or the X at the top-right).

With the method I mentioned, I have now discovered that only the second part is required: right-click on the (otherwise) unwanted Prospect Mail icon at the top bar of Gnome (Ubuntu). That both closes the window and resets the session.

**Comment by negesti** [comment]
@pkeir Right click on the top bar icon does not work for my. In my case right click on the icon opens a context menu and enable/disable the checkbox "Window Frame" reloads the prospect mail session and i can access my mails again

**Comment by pkeir** [comment]
Nice. This does work for me, though I find on the menu that pops up from the top bar icon, the choice is `Settings > Show Window Frame`.

The only disadvantage is that with `Show Window Frame` being a toggle, the window then appears without a frame, and so cannot be moved by the mouse as usual.

**Comment by pkeir** [comment]
Links seem now to be opening correctly in the browser for me.

**Comment by micw** [comment]
> {
>     "urlMainWindow":"https://outlook.live.com/mail",
>     "urlsInternal":["outlook.com", "live.com"],
>     "urlsExternal":["outlook.com", "live.com"]
> }

I wonder what the meaning of this setting is, it makes no sense to me. In the code, urlsInternal goes into the "deeplinkUrls" variable. "urlsExternal" goes to the "outlookUrls" variable. outlookUrls are always opened within the application's main window. For deeplinkUrls, the "default bahaviour" is used (I guess either the main window or a new application window).
All that does not match opens in an external browser.

I modified the code a bit locally to allow to force that some URLs are opened in an external browser. This way I can force "safelink.html" to be opened external although it matches the other domains which solves this issue for me. I will provide a PR for testing.

**Comment by pkeir** [comment]
> Links seem now to be opening correctly in the browser for me.

I spoke too soon: today a YouTube link once again opened within Prospect Mail.

**Comment by kbuzzard** [comment]
I'm afraid that I'm just using Prospect Mail via some package manager and am in no position to compile it myself.

**Comment by jclsn** [comment]
Any way to force the links to be opened in Firefox?

**Comment by kbuzzard** [comment]
Oh this is a great question: I've noticed that right now in my set-up the links are being opened in a new window but with no browser buttons (so e.g. you can't go back if you click on a link)

**Comment by jclsn** [comment]
The workaround needs to be changed to

```json
{
"urlMainWindow":"https://outlook.office.com/mail/",
"urlsInternal":["outlook.com", "live.com"],
"urlsExternal":["outlook.com", "live.com"]
}
```

now

**Comment by pkeir** [comment]
I tried the solution above. I edited `$HOME/snap/prospect-mail/current/.config/Prospect Mail/settings.json` as suggested. Now links open using a new Prospect Mail window (rather than your browser, with your browser settings).

It's certainly easier then to recover, but this is still not a proper fix.

**Comment by jclsn** [comment]
Yeah, there is another fix in a fork somewhere, but I was too lazy to build it myself.

**Comment by areyesco** [comment]
The problem is in the sniped code by paulquevedojdrf, but understanding the code, you only need to modify the property "urlsExternal" in the settings.json file with a customer random array string, to overwrite the default value. My in case I add this value for "urlsExternal":

File settings.json
{
...
"urlsExternal": ["_A_"]
...
}

Close and reopen prospect mail, and now all the links are open in a new web browser window.

**Comment by kbuzzard** [comment]
This opens the links in a new window of some sort but I still don't get the browser navigation buttons such as a "back" button, and I'm not logged into things like github if I click on a github link.

**Comment by justinvson-pd** [comment]
Still doesn't work with latest main build for me, links still open inside prospect client

built and installed using snap.

Also changing settings.json does not seem to have effect on this, either by setting urlsExternal to a weird value or setting the other suggested values.

**Comment by julian-alarcon** [comment]
Please try again @justinvson-pd . You could use the beta channel of snap with version 0.5-beta1
`sudo snap install prospect-mail --channel=beta`

**Comment by micw** [comment]
It should work. I run a build of that PR since I created it and had no single external link opened in the mail window.
