### ISSUE TITLE
Alert from Microsoft after login with this client

### ISSUE THREAD

**Issue by jerome-cui** [julian-alarcon/prospect-mail#280]
I received an alert mail with content like this after I login with this client:

`

Hello xxx,

Alert - User logged in from an outdated browser which needs to be upgraded.
--
`
The mail is from no-reply@cloudappsecurity.com

Seems we need to upgrade the electron version to latest.

**Comment by julian-alarcon** [comment]
Can you try with the latest beta version (0.5.0-beta1)?
`sudo snap install prospect-mail --channel=beta`

Also available here in other packages: https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.5.0-beta1

**Comment by mikekoumas** [comment]
After the update to the latest version we face the same issue. Prospect-mail loads Exchange web app in light mode. It seems that it sends outdated browser version for some reason. I tried the beta and still the same. Also installed deb instead of snap, same again.

**Comment by julian-alarcon** [comment]
@mikekoumas are you able to login and use your email after the message of out dated browser?

**Comment by mikekoumas** [comment]
@julian-alarcon we did not receive the message for the outdated browser because we use exchange in local environment. 
I do know that is the same issue as @jerome-cui  because when we login to the mailbox then the OWA that loads is the light one which most of the times [loads due to outdated browser](https://support.microsoft.com/en-us/office/learn-more-about-the-light-version-of-outlook-2aec8c2d-da48-4707-ba37-c800e1c284cd).

**Comment by jerome-cui** [comment]
Great works! No alert any more with version 0.5.1. Thanks for your help!
