### ISSUE TITLE
No Spell Check 

### ISSUE THREAD

**Issue by antonical** [julian-alarcon/prospect-mail#67]
There is no spell check when writing or editing any email or calendar event. 

It would be great to enable it.

Cheers

**Comment by cvillabrille** [comment]
Agree. I have been using it since a bit of time, and despite I think it's a perfect client to access Microsoft Outlook from Linux, I am missing the Spell checker. I understand the difficulties due to the plenty of languages but, I think the speller is a must nowadays specially for the non-native writers (or even for the natives too :))

Any plan or estimation time for so?

**Comment by racdamico** [comment]
Yes, I think the same. It'll be very useful to have spell checker on client.

**Comment by racdamico** [comment]
I've saw that your project is based on another one. This project has implemented spell checker. Is there a way to implement it?
[Link here](https://github.com/eNkru/freelook/commit/db74e3d485992c720e42fcac89b0585012ebb048)

thank you very much!

**Comment by julian-alarcon** [comment]
Duplicated https://github.com/julian-alarcon/prospect-mail/issues/15
