### ISSUE TITLE
Once opened meeting mail, there is no way to return back to Mailbox from there

### ISSUE THREAD

**Issue by PabitraPati** [julian-alarcon/prospect-mail#99]
Summary -  Once you have clicked on a meeting notification pop-up and opened the corresponding mail, there is no way to go back to the Mailbox from there.

**Steps**

1. Configure Prospect Mail on Ubuntu
2. Once a meeting is scheduled, a notification reminder will pop-up   
 ![Click Notification](https://user-images.githubusercontent.com/8273486/96411693-84ad8480-1206-11eb-8b6e-514cbe6e01c8.png)
 
 
3. Click on the pop-up, this will open the corresponding mail for the meeting invite.    
   ![No Way to Return](https://user-images.githubusercontent.com/8273486/96411692-84ad8480-1206-11eb-80a4-77ef8722c5b1.png)
 

Now, from the opened mail, **there is no way, that you can go back** to the All Mailbox. 
None of the Maibox options do provide the option to do so.

For now, only way to get back to mailbox is 
   - Kill the prospect Mail process using suod kill <PID> 
   - Reopen the prospect Mail

**Comment by nevadah-bfg** [comment]
This can also be reproduced with the following steps:

1. Click the My Day icon in the top toolbar to open the My Day sidebar.
2. Click on an upcoming event to view it.
3. At the top of the sidebar, click the icon next to the X that has the tooltip "View full event in new window."

The core cause of the problem is that, in the regular Outlook web UI, this will open a separate browser window to display the event. However, Prospect opens the page in the same window, and there is no navigation control to return.

**Comment by CloneMMDDCVII** [comment]
I share the issue.
It would be great if Prospect had an option to reset when similar events occur

**Comment by nevadah-bfg** [comment]
I played around with this a bit and it appears that simply removing lines 148 and 149 from mail-window-controller.js will fix this. I'm by no means an expert with JavaScript or Electron so it's entirely possible that this will result in other side effects but it worked fine in the limited testing I did.

In short, change this:
        else if (new RegExp(outlookUrls.join('|')).test(url)) {
            // Open calendar, contacts and tasks in the same window
            e.preventDefault()
            this.loadURL(url)
        }

to this:

        else if (new RegExp(outlookUrls.join('|')).test(url)) {
            // Open calendar, contacts and tasks in a new window
        }

You still need the if statement, otherwise it will open it in the default browser instead.

**Comment by julian-alarcon** [comment]
Duplicated of https://github.com/julian-alarcon/prospect-mail/issues/17
